
package com.msci.carrental.client.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarRentalServiceInterface", targetNamespace = "http://service.carrental.msci.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarRentalServiceInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.msci.carrental.client.ws.CarSpecification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDetailedSpecificationForACarType", targetNamespace = "http://service.carrental.msci.com/", className = "com.msci.carrental.client.ws.GetDetailedSpecificationForACarType")
    @ResponseWrapper(localName = "getDetailedSpecificationForACarTypeResponse", targetNamespace = "http://service.carrental.msci.com/", className = "com.msci.carrental.client.ws.GetDetailedSpecificationForACarTypeResponse")
    @Action(input = "http://service.carrental.msci.com/CarRentalServiceInterface/getDetailedSpecificationForACarTypeRequest", output = "http://service.carrental.msci.com/CarRentalServiceInterface/getDetailedSpecificationForACarTypeResponse")
    public CarSpecification getDetailedSpecificationForACarType(
        @WebParam(name = "arg0", targetNamespace = "")
        CarType arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.msci.carrental.client.ws.CarInstance>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableCarsForRental", targetNamespace = "http://service.carrental.msci.com/", className = "com.msci.carrental.client.ws.GetAvailableCarsForRental")
    @ResponseWrapper(localName = "getAvailableCarsForRentalResponse", targetNamespace = "http://service.carrental.msci.com/", className = "com.msci.carrental.client.ws.GetAvailableCarsForRentalResponse")
    @Action(input = "http://service.carrental.msci.com/CarRentalServiceInterface/getAvailableCarsForRentalRequest", output = "http://service.carrental.msci.com/CarRentalServiceInterface/getAvailableCarsForRentalResponse")
    public List<CarInstance> getAvailableCarsForRental();

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookACar", targetNamespace = "http://service.carrental.msci.com/", className = "com.msci.carrental.client.ws.BookACar")
    @ResponseWrapper(localName = "bookACarResponse", targetNamespace = "http://service.carrental.msci.com/", className = "com.msci.carrental.client.ws.BookACarResponse")
    @Action(input = "http://service.carrental.msci.com/CarRentalServiceInterface/bookACarRequest", output = "http://service.carrental.msci.com/CarRentalServiceInterface/bookACarResponse")
    public long bookACar(
        @WebParam(name = "arg0", targetNamespace = "")
        BookingRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.msci.carrental.client.ws.BookingResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookingResultsForIds", targetNamespace = "http://service.carrental.msci.com/", className = "com.msci.carrental.client.ws.GetBookingResultsForIds")
    @ResponseWrapper(localName = "getBookingResultsForIdsResponse", targetNamespace = "http://service.carrental.msci.com/", className = "com.msci.carrental.client.ws.GetBookingResultsForIdsResponse")
    @Action(input = "http://service.carrental.msci.com/CarRentalServiceInterface/getBookingResultsForIdsRequest", output = "http://service.carrental.msci.com/CarRentalServiceInterface/getBookingResultsForIdsResponse")
    public List<BookingResult> getBookingResultsForIds(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Long> arg0);

}
