
package com.msci.carrental.client.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarRentalServiceImplementationService", targetNamespace = "http://implementation.service.carrental.msci.com/", wsdlLocation = "http://localhost:8080/WS/CarRental?wsdl")
public class CarRentalServiceImplementationService
    extends Service
{

    private final static URL CARRENTALSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARRENTALSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName CARRENTALSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://implementation.service.carrental.msci.com/", "CarRentalServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/CarRental?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARRENTALSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        CARRENTALSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public CarRentalServiceImplementationService() {
        super(__getWsdlLocation(), CARRENTALSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public CarRentalServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARRENTALSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public CarRentalServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, CARRENTALSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public CarRentalServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARRENTALSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public CarRentalServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarRentalServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarRentalServiceInterface
     */
    @WebEndpoint(name = "CarRentalServiceImplementationPort")
    public CarRentalServiceInterface getCarRentalServiceImplementationPort() {
        return super.getPort(new QName("http://implementation.service.carrental.msci.com/", "CarRentalServiceImplementationPort"), CarRentalServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarRentalServiceInterface
     */
    @WebEndpoint(name = "CarRentalServiceImplementationPort")
    public CarRentalServiceInterface getCarRentalServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implementation.service.carrental.msci.com/", "CarRentalServiceImplementationPort"), CarRentalServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARRENTALSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw CARRENTALSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return CARRENTALSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
